version: '3.3'
services:
    hajk:
        ports:
            - '3000:3002'
        container_name: hajk
        image: hallbergs/hajk:latest
        volumes:
          - type: bind
            source: ./data/App_Data
            target: /usr/app/App_Data
          - type: bind
            source: ./data/logs
            target: /usr/app/logs
          - type: bind
            source: ./data/.env
            target: /usr/app/.env
          - type: bind
            source: ./data/tls-for-ldaps
            target: /usr/app/tls-for-ldaps
          - type: bind
            source: ./data/clientConfig.json
            target: /usr/app/static/client/appConfig.json
          - type: bind
            source: ./data/adminConfig.json
            target: /usr/app/static/admin/config.json
            